[package]
name = "bevy_spicy_aseprite"
version = "0.1.0"
description = "Compile time aseprite bevy integration"
edition = "2021"
resolver = "2"
license = "MIT OR Apache-2.0"
exclude = ["assets/"]
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["derive"]

[dependencies]
anyhow = "1.0.43"
aseprite-reader = { path = "../aseprite-reader" }
bevy = { git = "https://github.com/bevyengine/bevy.git", default-features = false, features = ["render"] }
bevy_spicy_aseprite_derive = { path = "./derive" }

[dev-dependencies]
tracing-log = "0.1.2"
bevy = { git = "https://github.com/bevyengine/bevy.git" }